server:
  port: 8081

spring:
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: example
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html

